### PR TITLE
Add Composer Support

### PR DESCRIPTION
**Pull request by huebs**
- [Composer](https://getcomposer.org) manifest added
- `/vendor/` directory added to `/.gitignore` file

### CODE REVIEW

**Comment by huebs** [comment]
Addresses #4

**Comment by huebs** [comment]
I tried my best to pull existing metadata from the [node-pdfcrowd](https://github.com/pdfcrowd/node-pdfcrowd) [`package.json`](https://github.com/pdfcrowd/node-pdfcrowd/blob/master/package.json), [pdfcrowd-python3](https://github.com/pdfcrowd/pdfcrowd-python3) [`setup.py`](https://github.com/pdfcrowd/pdfcrowd-python3/blob/master/setup.py) and [pdfcrowd-ruby](https://github.com/pdfcrowd/pdfcrowd-ruby) [`pdfcrowd.gemspec`](https://github.com/pdfcrowd/pdfcrowd-ruby/blob/master/pdfcrowd.gemspec) files but there were some conflicts in the data.

**Comment by davidkryzaniak** [comment]
Kudos! Closes #6

**Comment by foxmadr** [comment]
Composer is now supported.
`$ composer require pdfcrowd/pdfcrowd`

**Comment by huebs** [comment]
Yay!

**Pull request closed without merging**
